Add latest Google GSON library because of the following error from Stripe API:  - 'java.lang.NoClassDefFoundError: com/google/gson/Reflect AccessFilter' Add test to Stripe Service